version: '3.8'

networks:
    backend:

services:

    bot:
        container_name: bot_container
        image: bot_image
        build:
            context: .
            dockerfile: ./bot/Dockerfile
        ports:
            - "8080:8080"
            - "8090:8090"
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            SCRAPPER_URL: "http://scrapper:8081"
            RABBIT_HOST: "rabbitmq"
        networks:
            - backend
        deploy:
            restart_policy:
                delay: 5s
                condition: on-failure
                max_attempts: 5

    scrapper:
        container_name: scrapper_container
        image: scrapper_image
        build:
            context: .
            dockerfile: ./scrapper/Dockerfile
        ports:
            - "8081:8081"
            - "8091:8091"
        environment:
            GITHUB_TOKEN: ${GITHUB_TOKEN}
            DB_URL: "jdbc:postgresql://postgres:5432/scrapper"
            BOT_URL: "http://bot:8080"
            RABBIT_HOST: "rabbitmq"
        networks:
            - backend
        deploy:
            restart_policy:
                delay: 5s
                condition: on-failure
                max_attempts: 5

    postgres:
        container_name: postgres_container
        image: postgres
        environment:
            POSTGRES_DB: "scrapper"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "qwerty"
        volumes:
            - ./volumes/2. Init Database:/docker-entrypoint-initdb.d
            - ./volumes/postgres-data:/var/lib/postgresql/data
        networks:
            - backend
        ports:
            - "5434:5432"
        restart: unless-stopped
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 20s
            timeout: 5s
            retries: 5
            start_period: 10s

    liquibase-migrations:
        image: liquibase/liquibase:4.18
        depends_on:
            - postgres
        restart: on-failure
        command:
            - --hub-mode=off
            - --changelog-file=master.xml
            - --driver=org.postgresql.Driver
            - --url=jdbc:postgresql://postgres:5432/scrapper
            - --username=postgres
            - --password=qwerty
            - update
        volumes:
            - ./migrations:/liquibase/changelog
        networks:
            - backend
    rabbitmq:
        image: rabbitmq:3-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=qwerty
        volumes:
            - ./volumes/rabbitmq:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - backend

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./volumes/prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - "9090:9090"

    grafana:
        user: root
        image: grafana/grafana-oss
        volumes:
            - ./volumes/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - "3000:3000"
