app:
    test: test
    scheduler:
        interval: ${SCHEDULER_INTERVAL}
    database-access-type: jpa
    useQueue: true

rabbit:
    queue: scrapper-queue
    exchange: scrapper-exchange


scheduler:
    linkUpdate: ${TIME_UPDATE}
api:
    github:
        token: ${GITHUB_TOKEN}

baseUrl:
    github: https://api.github.com
    stackOverflow: https://api.stackexchange.com/2.3
    bot: ${BOT_URL}

default:
    timeout: 30

springdoc:
    swagger-ui:
        path: /swagger-ui.html
server:
    port: 8081

management:
    metrics:
        tags:
            application: ${spring.application.name}
    server:
        port: 8091
    endpoints:
        web:
            base-path: /
            path-mapping:
                prometheus: metrics
            exposure:
                include: "*"
        enabled-by-default: false

    endpoint:
        info:
            enabled: true
        health:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true
    prometheus:
        metrics:
            export:
                enabled: true

spring:
    jpa:
        defer-datasource-initialization: false
        properties:
            hibernate:
                format_sql: true
                generate_statistics: false
                jdbc:
                    batch_size: 50
                    fetch_size: 50
                order_updates: true
                order_insert: true
        open-in-view: true
        show-sql: true
        hibernate:
            ddl-auto: none
    datasource:
        url: ${DB_URL}
        username: postgres
        password: qwerty
        driver-class-name: org.postgresql.Driver

    rabbitmq:
        host: ${RABBIT_HOST}
        username: user
        password: qwerty
        port: 5672
    application:
        name: scrapper
