app:
    test: value
    token: ${BOT_TOKEN}

rabbit:
    queue: scrapper-queue
    exchange: scrapper-exchange

baseUrl:
    scrapper: ${SCRAPPER_URL}

default:
    timeout: 5

server:
    port: 8080

management:
    prometheus:
        metrics:
            export:
                enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
    server:
        port: 8090
    endpoints:
        web:
            base-path: /
            path-mapping:
                prometheus: metrics
            exposure:
                include: "*"
        enabled-by-default: false

    endpoint:
        info:
            enabled: true
        health:
            enabled: true
        metrics:
            enabled: true
        prometheus:
            enabled: true

spring:
    application:
        name: bot
    rabbitmq:
        host: ${RABBIT_HOST}
        username: user
        password: qwerty
        port: 5672
        listener:
            simple:
                default-requeue-rejected: false
