app:
    test: value
    token: ${BOT_TOKEN}

rabbit:
    queue: scrapper-queue
    exchange: scrapper-exchange

baseUrl:
    scrapper: http://localhost:8081

default:
    timeout: 5

server:
    port: 8080

spring:
    rabbitmq:
        host: localhost
        username: user
        password: qwerty
        port: 5672
        listener:
            simple:
                default-requeue-rejected: false