name: scrapper CI/CD

on:
    push:
        paths:
            - 'scrapper/**'

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: scrapper_app

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven
            -   name: Build with Maven
                run: mvn package -pl scrapper -am

            -   name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GIT_TOKEN }}

            -   name: Build Docker image
                run: docker build -f ./scrapper/Dockerfile -t ${{ env.REGISTRY}}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest .

            -   name: Push Docker image
                run: docker push ${{ env.REGISTRY}}/${{ github.actor }}/${{ env.IMAGE_NAME }}:latest
    checkstyle:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
                    cache: maven

            -   name: Prepare checkstyle
                run: mvn clean install

            -   name: Run Checkstyle
                run: mvn -pl scrapper -am checkstyle:check
